---
# tasks file for ansible-role-ohpc-repo

- name: get OpenHPC Repo
  yum: name={{ openhpc_release7_rpm }} state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: get OpenHPC Repo
  dnf: name={{ openhpc_release8_rpm }} state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
